language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8.11.1'
  - stable
os:
  - osx
before_install: npm i rxjs@6.0.0-beta.0 @angular/core@6.0.0-rc.0 @angular/compiler@6.0.0-rc.0 zone.js@0.8.20

after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
