version: 2

aliases:
  - &restore-cache-deps
      key: dependency-cache-{{ checksum "package.json" }}

  - &save-cache-deps
      key: dependency-cache-{{ checksum "package.json" }}
      paths:
        - node_modules

defaults: &defaults
  working_directory: /tmp/workspace
  docker:
    - image: circleci/node:latest

general:
  artifacts:
    - "./coverage/"

jobs:
  build_and_test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache-deps
      - run: npm install
      - save_cache: *save-cache-deps
      - run: npm run lint
      - run: npm run format:check
      - run: npm run build
      - run: mkdir junit
      - run: 
          command: npm run test:ci
          environment:
            MOCHA_FILE: junit/test-results.xml
          when: always
      - run: npm run test:coverage
      - store_test_results:
          path: junit
      - store_artifacts:
          path: junit
          path: coverage

workflows:
  version: 2
  build:
    jobs:
      - build_and_test
      # - deploy:
      #     requires: [test]
      #     filters:
      #       branches:
      #         only: master
